import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NavigationMenuDemo } from '../components/nav';
import Header from '@/components/header';
import { Sidebar } from '@/components/sidebar';
import { categories } from '@/data/categories';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} grid`}>
        {/* <Sidebar categories={categories} className="w-full md:w-64"/> */}
        <main className="w-full flex-grow grid place-items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
